spring.application.name=nextcar

# Spring DataSource Configuration (PostgreSQL)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring Data JPA Configuration
spring.jpa.show-sql=true

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Configuration
server.port=8091

spring.jpa.hibernate.naming.physical-strategy=org.pe.nextcar.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy
# Elements that take values from pom.xml
documentation.application.version=@project.version@
documentation.application.description=@project.description@

# JWT Configuration Properties
authorization.jwt.secret=WriteHereYourSecretStringForTokenSigningCredentials
authorization.jwt.expiration.days=7


# SWAGGER URL: http://localhost:8091/swagger-ui/index.html#/


# reCAPTCHA
recaptcha.secret-key=${GOOGLE_CAPTCHA_KEY:}
recaptcha.min-score=0.5

# API Peru (DNI)
apiperu.token=${APIPERU_DNI_KEY}
apiperu.base-url=https://apiperu.dev/api
apiperu.enabled=true

# Logging
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
